<a href="https://colab.research.google.com/github/DhruvRajSingh-Coder/LetsUpgrade-AI-ML/blob/master/Day_15_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.
Create a 3x3x3 array with random values.

In [159]:
import numpy as np
D=np.random.random((3,3,3))
print(D)

[[[0.92893974 0.51748394 0.02402985]
  [0.72275107 0.20776251 0.92907233]
  [0.84761035 0.26975306 0.30507237]]

 [[0.33554476 0.05509915 0.50145733]
  [0.38519127 0.45688215 0.01881213]
  [0.8992345  0.64751668 0.45462292]]

 [[0.71028876 0.98416044 0.7931729 ]
  [0.6133497  0.63683053 0.10335003]
  [0.65168819 0.95672546 0.04102824]]]


2.
Create a 5x5 matrix with values 1,2,3,4 just below the
diagonal.

In [160]:
K=np.diag(1+np.arange(4),-1)
print(K)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


3.
Create a 8x8 matrix and fill it with a checkerboardpattern.

In [161]:
B=np.zeros((8,8),dtype=int)
B[1::2,::2]=1
B[::2,1::2]=1
print(B)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


4.
Normalize a 5x5 random matrix.

In [162]:
S=np.random.random((5,5))
print(S,"\n")
Smin,Smax=S.min(),S.max()
S=S-Smin/Smax-Smin
print(S)

[[0.39875494 0.02293163 0.20115112 0.34970877 0.76098339]
 [0.25305296 0.91661473 0.35578243 0.74537268 0.37523974]
 [0.40700559 0.31010651 0.43216801 0.65797973 0.00364584]
 [0.59492554 0.21152269 0.85456559 0.26602597 0.52130606]
 [0.81315593 0.23006469 0.59244285 0.72470198 0.484961  ]] 

[[ 0.39113159  0.01530828  0.19352777  0.34208542  0.75336004]
 [ 0.24542961  0.90899138  0.34815908  0.73774933  0.36761639]
 [ 0.39938224  0.30248316  0.42454466  0.65035638 -0.00397751]
 [ 0.58730219  0.20389934  0.84694224  0.25840262  0.51368271]
 [ 0.80553258  0.22244134  0.5848195   0.71707863  0.47733765]]


5.
How to find common values between two arrays?

In [163]:
A1=[6,7,12,21,23,58]
A2=[6,9,11,12,15,21,24]
D=np.intersect1d(A1,A2)
print(D)

[ 6 12 21]


6.
How to get the dates of yesterday, today and tomorrow?

In [164]:
import datetime as dt
today=dt.date.today()
yesterday=today-dt.timedelta(days=1)
tomorrow=today+dt.timedelta(days=1)
print("Yesterday was ", yesterday)
print("Today is ", today)
print("Tomorrow will be ", tomorrow)

Yesterday was  2020-07-27
Today is  2020-07-28
Tomorrow will be  2020-07-29


7.
Consider two random array A and B,check if they are equal.

In [232]:
A=np.random.randint(2,size=3)
print (A)
B=np.random.randint(2,size=3)
print (B)
D=np.array_equal(A,B)
print (D)

[0 0 1]
[0 0 1]
True


8.
Create random vector of size 10 and replace the maximum value by 0.

In [ ]:
R=np.random.randint(13,size=10)
print (R)
R[R.argmax()]=0
print (R)

[ 4  9 11  2  1 12  9  1 10  9]
[ 4  9 11  2  1  0  9  1 10  9]


9.
How to print all the values of an array?

In [ ]:
F=np.random.randint(10,size=999)
np.set_printoptions(threshold=np.inf)
print (F)

[5 0 8 4 1 5 9 4 1 7 4 0 5 8 2 9 0 3 4 8 5 1 2 6 8 6 1 4 4 3 9 3 0 0 5 6 5
 0 5 8 9 2 8 4 0 2 4 8 1 4 5 9 5 8 1 4 0 9 6 7 0 2 0 5 4 5 8 8 0 9 2 3 1 8
 2 3 3 7 3 8 3 2 9 9 7 7 7 5 4 4 0 3 1 8 7 3 2 0 9 1 0 7 4 8 6 0 8 7 3 9 3
 9 3 3 4 2 1 7 0 7 6 2 4 1 8 9 0 5 0 3 3 4 6 1 3 9 3 1 8 6 1 9 2 6 8 4 7 9
 0 5 3 6 6 5 8 3 8 7 3 5 7 0 4 7 8 6 8 9 1 5 4 1 5 3 2 7 4 0 6 7 7 5 9 2 7
 7 4 9 9 3 4 1 1 2 1 0 3 6 8 0 9 2 0 2 7 2 0 4 6 7 8 0 3 5 7 1 2 3 4 1 0 9
 5 2 8 9 8 4 8 2 4 3 8 0 8 1 9 5 7 5 4 9 4 1 1 7 1 5 3 1 5 7 5 4 3 3 2 9 2
 5 3 0 3 5 6 4 0 0 8 1 0 5 6 4 0 9 3 2 8 1 8 0 3 5 9 3 7 0 4 9 2 8 9 8 4 1
 0 9 4 8 1 5 8 6 3 8 9 1 7 9 0 3 7 1 5 2 9 8 8 7 7 1 2 8 2 3 5 3 6 2 6 0 9
 2 6 3 9 9 7 8 8 7 4 3 1 3 9 7 5 0 4 2 3 7 0 4 5 9 0 8 0 5 0 7 5 7 7 9 5 7
 3 3 2 2 4 6 8 1 9 1 4 1 6 6 8 9 7 5 1 9 1 9 4 2 2 5 1 6 8 9 0 5 6 9 2 2 3
 5 7 0 8 7 7 4 0 7 2 6 3 5 3 7 3 5 6 8 5 2 5 8 1 6 7 6 9 6 3 3 5 7 3 1 2 2
 3 8 4 6 4 2 2 4 6 5 3 1 2 4 1 2 9 8 6 5 3 0 2 3 6 4 9 1 1 3 2 3 6 7 5 6 9
 6 7 9 1 8 6 4 7 4 8 4 7 

10.
Subtract the mean of each row of a matrix.

In [ ]:
R=np.array([[1,2,3],[4,5,6],[7,8,9]])
print (R)
Mean=R.mean(axis=1,keepdims=True)
print("Mean of each row is \n",Mean)
R1=print("Resultant matrix is \n",R-Mean)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Mean of each row is 
 [[2.]
 [5.]
 [8.]]
Resultant matrix is 
 [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


11.
Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeatedindices)?

In [ ]:
A=np.random.randint(0,9,10)
print (A)
B=np.random.randint(0,7,10)
print (B)
A+=np.bincount(B,minlength=len(A))
print (A)

[7 7 4 6 2 5 6 0 4 7]
[4 2 1 1 1 6 2 4 1 1]
[ 7 12  6  6  4  5  7  0  4  7]


12.
How to get the diagonal of a dot product?

In [129]:
U=np.random.randint(0,13,(3,3))
print (U)
V=np.random.randint(0,13,(3,3))
print (V)
print ("The diagonal of the dot product is \n",(np.diag(np.dot(U,V))))

[[12  7 11]
 [12  5  3]
 [ 7  5 12]]
[[ 4 12  6]
 [ 2 12  8]
 [ 6  2  9]]
The diagonal of the dot product is 
 [128 210 190]


13.
How to find the most frequent value in an array?

In [140]:
D=np.random.randint(0,10,20)
print (D)
print ("Most frequent value is ",np.bincount(D).argmax())

[3 6 5 7 6 6 9 2 1 4 0 5 7 8 3 8 0 4 1 9]
Most frequent value is  6


14.
How to get the n largest values of an array.

In [141]:
K=np.arange(100)
np.random.shuffle(K)
n=7
print (n,"Largest values are \n")
print (K[np.argsort(K)[-n:]])

7 Largest values are 

[93 94 95 96 97 98 99]


15.
How to create a record array from a regular array?

In [155]:
X=np.array([("Dhruv",6.7,12),
            ("Raj",7.58,21)])
Y=np.core.records.fromarrays(X.T,names='col1,col2,col3',formats='S8,f8,i8')
print (Y)

[(b'Dhruv', 6.7 , 12) (b'Raj', 7.58, 21)]
