___Q.  Perform Naive Bayes Algorithm on the Train dataset.___

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,confusion_matrix

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
path='/content/drive/My Drive/train.csv'
Data=pd.read_csv(path)
Data.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [5]:
Data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [6]:
Data=Data.drop(["PassengerId","Name","Ticket","Cabin"],axis=1)
Data.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [7]:
Data.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [8]:
Data.describe().T

count       mean        std   min      25%      50%   75%       max
Survived  891.0   0.383838   0.486592  0.00   0.0000   0.0000   1.0    1.0000
Pclass    891.0   2.308642   0.836071  1.00   2.0000   3.0000   3.0    3.0000
Age       714.0  29.699118  14.526497  0.42  20.1250  28.0000  38.0   80.0000
SibSp     891.0   0.523008   1.102743  0.00   0.0000   0.0000   1.0    8.0000
Parch     891.0   0.381594   0.806057  0.00   0.0000   0.0000   0.0    6.0000
Fare      891.0  32.204208  49.693429  0.00   7.9104  14.4542  31.0  512.3292

In [9]:
new_age=np.where(Data["Age"].isnull(),29,Data["Age"])
Data["Age"]=new_age

In [10]:
Data=Data.dropna()
Data.isnull().sum().sum()

0

In [11]:
Data.duplicated().sum()

114

In [12]:
Data=Data.drop_duplicates()
Data.duplicated().sum()

0

In [13]:
le=LabelEncoder()
Data['Sex']=le.fit_transform(Data['Sex'])
Data['Embarked']=le.fit_transform(Data['Embarked'])
Data.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [40]:
def Nav_Model(col):
  x=Data.drop([col],axis=1)
  y=Data[col]
  x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)
  model=GaussianNB()
  model.fit(x_train,y_train)
  y_pred=model.predict(x_test)
  print(f"Accuracy score of the model is {accuracy_score(y_test,y_pred)}")
  print(f"Confusion matrix:\n{confusion_matrix(y_test,y_pred)}")

In [41]:
Nav_Model('Pclass')

Accuracy score of the model is 0.7253218884120172
Confusion matrix:
[[53 14  4]
 [ 4 29 23]
 [ 2 17 87]]


In [42]:
Nav_Model('Sex')

Accuracy score of the model is 0.7811158798283262
Confusion matrix:
[[ 69  19]
 [ 32 113]]


In [43]:
Nav_Model('SibSp')

Accuracy score of the model is 0.4592274678111588
Confusion matrix:
[[88  7  3 53  1]
 [34 11  1 22  1]
 [ 2  0  0  2  0]
 [ 0  0  0  3  0]
 [ 0  0  0  0  5]]


In [44]:
Nav_Model('Parch')

Accuracy score of the model is 0.7553648068669528
Confusion matrix:
[[167  10   0   1   0]
 [ 20   6   9   0   0]
 [ 12   2   3   0   0]
 [  0   0   0   0   0]
 [  2   1   0   0   0]]


In [45]:
Nav_Model('Embarked')

Accuracy score of the model is 0.5064377682403434
Confusion matrix:
[[18  9 21]
 [ 1  6  4]
 [20 60 94]]
